apiVersion: v1
kind: Secret
metadata:
  name: kaniko-secret
  namespace: jenkins
type: Opaque
data:
  config.json: ewogICAgYXV0aHM6IHsKICAgICAgaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvOiB7CiAgICAgICAgYXV0aDogYldGeWEySnZkSEp2Y3pwTmJVQXpNREE1T1RnSwogICAgICB9CiAgICB9CiAgfQogIAo=